#!/bin/bash
#Project 3 CIT470
#Darci Guriel
#Austin Kelly, Kasey Cottier, Randy Clark, Chris Pischl, and Zoey Koza
#Finalizes Monit & Syslog Configuration from Kickstart Installs
if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
  echo "Usage: `basename $0` [The script must be ran as followed: ./client_config_script 'Your Server IP' 'System Log Email']" | tee -a monit-setup.log ; exit 0 ;
else
#Removes default monit cfg file, downloads modified version and creates a backup
echo "Configuring Monit..." | tee -a monit-setup.log && rm /etc/monitrc >& 1 >> monit-setup.log
wget -O monitrc https://raw.githubusercontent.com/kellya14/project3/master/monitrc_client | tee -a monit-setup.log
mv monitrc /etc/monitrc && cp /etc/monitrc /etc/monitrc.bak >& 1 >> monit-setup.log && chmod 600 /etc/monitrc >& 1 >> monit-setup.log &&
#Passes script arguments to the monit configuration file
sed -i "s/root@localhost/root@$1/g" /etc/monitrc >& 1 >> monit-setup.log && sed -i "s/alert emailhere/alert $2/g" /etc/monitrc >& 1 >> monit-setup.log &&
#restart monit service
echo "Restarting Monit service..." | tee -a monit-setup.log && systemctl restart monit >& 1 >> monit-setup.log && echo "Configuration complete!" | tee -a monit-setup.log
#appends the serverIP to the syslog cfg file for remote logging
echo "Configuring remote monitoring..." | tee -a monit-setup.log && sed -i "s/#*.* @@remote-host:514/*.* @$1:514/g" /etc/rsyslog.conf >& 1 >> monit-setup.log && systemctl restart rsyslog >& 1 >> monit-setup.log && echo "Setup complete!" | tee -a monit-setup.log
#Configure firewall for syslog and monit.
firewall-cmd --zone=public --add-port=514/udp -–permanent | tee -a monit-setup.log
firewall-cmd --zone=public --add-port=2812/tcp -–permanent | tee -a monit-setup.log
firewall-cmd --reload | tee -a monit-setup.log
fi
