#!/bin/bash
#Project 3 CIT470
#Darci Guriel
#Austin Kelly, Kasey Cottier, Randy Clark, Chris Pischl, and Zoey Koza
#Finalizes Monit & Syslog Configuration from Kickstart Installs

#if [ "$1" == "-h" ] || [ "$1" == "--help" ]
#then
#  echo "Usage: `basename $0` [Start the LDAP Server script by using this command: ./install-ldap-server]" | tee -a ldap-install.log
#else

#Help menu that displays the script deployment syntax
if [ "$1" == "-h" ] ; then echo "Usage: `basename $0` [The script must be ran as followed: ./client-monit 'ServerIP' 'AdminEmail']" ; exit 0 ; fi

monit_cfg="/etc/monitrc"

#Removes default monit cfg file, downloads modified version and creates a backup
echo "Configuring Monit..." | tee -a monit-setup.log && rm /etc/monitrc >& 1 >> monit-setup.log && wget http://10.2.6.19/~apache-user/monitrc -P /etc/ >& 1 >> monit-setup.log && cp /etc/monitrc /etc/monitrc.bak >& 1 >> monit-setup.log && chmod 600 /etc/monitrc >& 1 >> monit-setup.log &&

#Passes script arguments to the monit cfg file
sed -i "s/root@localhost/root@$1/g" $monit_cfg >& 1 >> monit-setup.log && sed -i "s/alert emailhere/alert $2/g" $monit_cfg >& 1 >> monit-setup.log &&

#restart monit service
echo "Restarting Monit service" | tee -a monit-setup.log && systemctl restart monit >& 1 >> monit-setup.log && echo "Configuration complete!" | tee -a monit-setup.log

#appends the serverIP to the syslog cfg file for remote logging
echo "Setting up remote logging..." | tee -a monit-setup.log && sed -i "s/#*.* @@remote-host:514/*.* @$1:514/g" /etc/rsyslog.conf >& 1 >> monit-setup.log && systemctl restart rsyslog >& 1 >> monit-setup.log && echo "Setup complete!" | tee -a monit-setup.log
